######################################################################
# Automatically generated by qmake (3.0) ?? 12? 16 10:06:47 2017
######################################################################

TEMPLATE = app
TARGET = Snake
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += snake.h
SOURCES += main.cpp snake.cpp
