######################################################################
# Automatically generated by qmake (3.0) ?? 12? 16 10:02:20 2017
######################################################################

TEMPLATE = app
TARGET = Snake
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += snake.h \
    FoodItem.h \
    SnakeItem.h \
    ConstValue.h
SOURCES += main.cpp snake.cpp \
    FoodItem.cpp \
    SnakeItem.cpp
